//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_khadamatiSubServices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMART_khadamatiSubServices.khadamati_ServicesSoap")]
    public interface khadamati_ServicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMART_khadamatiMainServices", ReplyAction="*")]
        System.Threading.Tasks.Task<SMART_khadamatiSubServices.SMART_khadamatiMainServicesResponse> SMART_khadamatiMainServicesAsync(SMART_khadamatiSubServices.SMART_khadamatiMainServicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMART_khadamatiSubServices", ReplyAction="*")]
        System.Threading.Tasks.Task<SMART_khadamatiSubServices.SMART_khadamatiSubServicesResponse> SMART_khadamatiSubServicesAsync(SMART_khadamatiSubServices.SMART_khadamatiSubServicesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_khadamatiMainServicesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_khadamatiMainServices", Namespace="http://tempuri.org/", Order=0)]
        public SMART_khadamatiSubServices.SMART_khadamatiMainServicesRequestBody Body;
        
        public SMART_khadamatiMainServicesRequest()
        {
        }
        
        public SMART_khadamatiMainServicesRequest(SMART_khadamatiSubServices.SMART_khadamatiMainServicesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_khadamatiMainServicesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Lang;
        
        public SMART_khadamatiMainServicesRequestBody()
        {
        }
        
        public SMART_khadamatiMainServicesRequestBody(string Lang)
        {
            this.Lang = Lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_khadamatiMainServicesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_khadamatiMainServicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMART_khadamatiSubServices.SMART_khadamatiMainServicesResponseBody Body;
        
        public SMART_khadamatiMainServicesResponse()
        {
        }
        
        public SMART_khadamatiMainServicesResponse(SMART_khadamatiSubServices.SMART_khadamatiMainServicesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_khadamatiMainServicesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMART_khadamatiMainServicesResult;
        
        public SMART_khadamatiMainServicesResponseBody()
        {
        }
        
        public SMART_khadamatiMainServicesResponseBody(string SMART_khadamatiMainServicesResult)
        {
            this.SMART_khadamatiMainServicesResult = SMART_khadamatiMainServicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_khadamatiSubServicesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_khadamatiSubServices", Namespace="http://tempuri.org/", Order=0)]
        public SMART_khadamatiSubServices.SMART_khadamatiSubServicesRequestBody Body;
        
        public SMART_khadamatiSubServicesRequest()
        {
        }
        
        public SMART_khadamatiSubServicesRequest(SMART_khadamatiSubServices.SMART_khadamatiSubServicesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_khadamatiSubServicesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MainServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Lang;
        
        public SMART_khadamatiSubServicesRequestBody()
        {
        }
        
        public SMART_khadamatiSubServicesRequestBody(int MainServiceID, int Lang)
        {
            this.MainServiceID = MainServiceID;
            this.Lang = Lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_khadamatiSubServicesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_khadamatiSubServicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMART_khadamatiSubServices.SMART_khadamatiSubServicesResponseBody Body;
        
        public SMART_khadamatiSubServicesResponse()
        {
        }
        
        public SMART_khadamatiSubServicesResponse(SMART_khadamatiSubServices.SMART_khadamatiSubServicesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_khadamatiSubServicesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMART_khadamatiSubServicesResult;
        
        public SMART_khadamatiSubServicesResponseBody()
        {
        }
        
        public SMART_khadamatiSubServicesResponseBody(string SMART_khadamatiSubServicesResult)
        {
            this.SMART_khadamatiSubServicesResult = SMART_khadamatiSubServicesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface khadamati_ServicesSoapChannel : SMART_khadamatiSubServices.khadamati_ServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class khadamati_ServicesSoapClient : System.ServiceModel.ClientBase<SMART_khadamatiSubServices.khadamati_ServicesSoap>, SMART_khadamatiSubServices.khadamati_ServicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public khadamati_ServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(khadamati_ServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), khadamati_ServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public khadamati_ServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(khadamati_ServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public khadamati_ServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(khadamati_ServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public khadamati_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMART_khadamatiSubServices.SMART_khadamatiMainServicesResponse> SMART_khadamatiSubServices.khadamati_ServicesSoap.SMART_khadamatiMainServicesAsync(SMART_khadamatiSubServices.SMART_khadamatiMainServicesRequest request)
        {
            return base.Channel.SMART_khadamatiMainServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMART_khadamatiSubServices.SMART_khadamatiMainServicesResponse> SMART_khadamatiMainServicesAsync(string Lang)
        {
            SMART_khadamatiSubServices.SMART_khadamatiMainServicesRequest inValue = new SMART_khadamatiSubServices.SMART_khadamatiMainServicesRequest();
            inValue.Body = new SMART_khadamatiSubServices.SMART_khadamatiMainServicesRequestBody();
            inValue.Body.Lang = Lang;
            return ((SMART_khadamatiSubServices.khadamati_ServicesSoap)(this)).SMART_khadamatiMainServicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMART_khadamatiSubServices.SMART_khadamatiSubServicesResponse> SMART_khadamatiSubServices.khadamati_ServicesSoap.SMART_khadamatiSubServicesAsync(SMART_khadamatiSubServices.SMART_khadamatiSubServicesRequest request)
        {
            return base.Channel.SMART_khadamatiSubServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMART_khadamatiSubServices.SMART_khadamatiSubServicesResponse> SMART_khadamatiSubServicesAsync(int MainServiceID, int Lang)
        {
            SMART_khadamatiSubServices.SMART_khadamatiSubServicesRequest inValue = new SMART_khadamatiSubServices.SMART_khadamatiSubServicesRequest();
            inValue.Body = new SMART_khadamatiSubServices.SMART_khadamatiSubServicesRequestBody();
            inValue.Body.MainServiceID = MainServiceID;
            inValue.Body.Lang = Lang;
            return ((SMART_khadamatiSubServices.khadamati_ServicesSoap)(this)).SMART_khadamatiSubServicesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.khadamati_ServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.khadamati_ServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.khadamati_ServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://unifiedgate.moj.gov.ae/soap_uaepass/khadamati_Services.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.khadamati_ServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://unifiedgate.moj.gov.ae/soap_uaepass/khadamati_Services.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            khadamati_ServicesSoap,
            
            khadamati_ServicesSoap12,
        }
    }
}
