//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_UAEPassCall
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_UAEPassCall.Service_UAEPassCallSoap")]
    public interface Service_UAEPassCallSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMART_GetDetailsByEID", ReplyAction="*")]
        System.Threading.Tasks.Task<Service_UAEPassCall.SMART_GetDetailsByEIDResponse> SMART_GetDetailsByEIDAsync(Service_UAEPassCall.SMART_GetDetailsByEIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAEPass_LogOut", ReplyAction="*")]
        System.Threading.Tasks.Task<Service_UAEPassCall.UAEPass_LogOutResponse> UAEPass_LogOutAsync(Service_UAEPassCall.UAEPass_LogOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMART_UnifiedGetURL", ReplyAction="*")]
        System.Threading.Tasks.Task<Service_UAEPassCall.SMART_UnifiedGetURLResponse> SMART_UnifiedGetURLAsync(Service_UAEPassCall.SMART_UnifiedGetURLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_GetDetailsByEIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_GetDetailsByEID", Namespace="http://tempuri.org/", Order=0)]
        public Service_UAEPassCall.SMART_GetDetailsByEIDRequestBody Body;
        
        public SMART_GetDetailsByEIDRequest()
        {
        }
        
        public SMART_GetDetailsByEIDRequest(Service_UAEPassCall.SMART_GetDetailsByEIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_GetDetailsByEIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonData;
        
        public SMART_GetDetailsByEIDRequestBody()
        {
        }
        
        public SMART_GetDetailsByEIDRequestBody(string jsonData)
        {
            this.jsonData = jsonData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_GetDetailsByEIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_GetDetailsByEIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Service_UAEPassCall.SMART_GetDetailsByEIDResponseBody Body;
        
        public SMART_GetDetailsByEIDResponse()
        {
        }
        
        public SMART_GetDetailsByEIDResponse(Service_UAEPassCall.SMART_GetDetailsByEIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_GetDetailsByEIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMART_GetDetailsByEIDResult;
        
        public SMART_GetDetailsByEIDResponseBody()
        {
        }
        
        public SMART_GetDetailsByEIDResponseBody(string SMART_GetDetailsByEIDResult)
        {
            this.SMART_GetDetailsByEIDResult = SMART_GetDetailsByEIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UAEPass_LogOutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UAEPass_LogOut", Namespace="http://tempuri.org/", Order=0)]
        public Service_UAEPassCall.UAEPass_LogOutRequestBody Body;
        
        public UAEPass_LogOutRequest()
        {
        }
        
        public UAEPass_LogOutRequest(Service_UAEPassCall.UAEPass_LogOutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UAEPass_LogOutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResponseURI;
        
        public UAEPass_LogOutRequestBody()
        {
        }
        
        public UAEPass_LogOutRequestBody(string ResponseURI)
        {
            this.ResponseURI = ResponseURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UAEPass_LogOutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UAEPass_LogOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Service_UAEPassCall.UAEPass_LogOutResponseBody Body;
        
        public UAEPass_LogOutResponse()
        {
        }
        
        public UAEPass_LogOutResponse(Service_UAEPassCall.UAEPass_LogOutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UAEPass_LogOutResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UAEPass_LogOutResult;
        
        public UAEPass_LogOutResponseBody()
        {
        }
        
        public UAEPass_LogOutResponseBody(string UAEPass_LogOutResult)
        {
            this.UAEPass_LogOutResult = UAEPass_LogOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_UnifiedGetURLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_UnifiedGetURL", Namespace="http://tempuri.org/", Order=0)]
        public Service_UAEPassCall.SMART_UnifiedGetURLRequestBody Body;
        
        public SMART_UnifiedGetURLRequest()
        {
        }
        
        public SMART_UnifiedGetURLRequest(Service_UAEPassCall.SMART_UnifiedGetURLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_UnifiedGetURLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonData;
        
        public SMART_UnifiedGetURLRequestBody()
        {
        }
        
        public SMART_UnifiedGetURLRequestBody(string jsonData)
        {
            this.jsonData = jsonData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMART_UnifiedGetURLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMART_UnifiedGetURLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Service_UAEPassCall.SMART_UnifiedGetURLResponseBody Body;
        
        public SMART_UnifiedGetURLResponse()
        {
        }
        
        public SMART_UnifiedGetURLResponse(Service_UAEPassCall.SMART_UnifiedGetURLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMART_UnifiedGetURLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMART_UnifiedGetURLResult;
        
        public SMART_UnifiedGetURLResponseBody()
        {
        }
        
        public SMART_UnifiedGetURLResponseBody(string SMART_UnifiedGetURLResult)
        {
            this.SMART_UnifiedGetURLResult = SMART_UnifiedGetURLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Service_UAEPassCallSoapChannel : Service_UAEPassCall.Service_UAEPassCallSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service_UAEPassCallSoapClient : System.ServiceModel.ClientBase<Service_UAEPassCall.Service_UAEPassCallSoap>, Service_UAEPassCall.Service_UAEPassCallSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service_UAEPassCallSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service_UAEPassCallSoapClient.GetBindingForEndpoint(endpointConfiguration), Service_UAEPassCallSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service_UAEPassCallSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service_UAEPassCallSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service_UAEPassCallSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service_UAEPassCallSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service_UAEPassCallSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Service_UAEPassCall.SMART_GetDetailsByEIDResponse> Service_UAEPassCall.Service_UAEPassCallSoap.SMART_GetDetailsByEIDAsync(Service_UAEPassCall.SMART_GetDetailsByEIDRequest request)
        {
            return base.Channel.SMART_GetDetailsByEIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Service_UAEPassCall.SMART_GetDetailsByEIDResponse> SMART_GetDetailsByEIDAsync(string jsonData)
        {
            Service_UAEPassCall.SMART_GetDetailsByEIDRequest inValue = new Service_UAEPassCall.SMART_GetDetailsByEIDRequest();
            inValue.Body = new Service_UAEPassCall.SMART_GetDetailsByEIDRequestBody();
            inValue.Body.jsonData = jsonData;
            return ((Service_UAEPassCall.Service_UAEPassCallSoap)(this)).SMART_GetDetailsByEIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Service_UAEPassCall.UAEPass_LogOutResponse> Service_UAEPassCall.Service_UAEPassCallSoap.UAEPass_LogOutAsync(Service_UAEPassCall.UAEPass_LogOutRequest request)
        {
            return base.Channel.UAEPass_LogOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Service_UAEPassCall.UAEPass_LogOutResponse> UAEPass_LogOutAsync(string ResponseURI)
        {
            Service_UAEPassCall.UAEPass_LogOutRequest inValue = new Service_UAEPassCall.UAEPass_LogOutRequest();
            inValue.Body = new Service_UAEPassCall.UAEPass_LogOutRequestBody();
            inValue.Body.ResponseURI = ResponseURI;
            return ((Service_UAEPassCall.Service_UAEPassCallSoap)(this)).UAEPass_LogOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Service_UAEPassCall.SMART_UnifiedGetURLResponse> Service_UAEPassCall.Service_UAEPassCallSoap.SMART_UnifiedGetURLAsync(Service_UAEPassCall.SMART_UnifiedGetURLRequest request)
        {
            return base.Channel.SMART_UnifiedGetURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Service_UAEPassCall.SMART_UnifiedGetURLResponse> SMART_UnifiedGetURLAsync(string jsonData)
        {
            Service_UAEPassCall.SMART_UnifiedGetURLRequest inValue = new Service_UAEPassCall.SMART_UnifiedGetURLRequest();
            inValue.Body = new Service_UAEPassCall.SMART_UnifiedGetURLRequestBody();
            inValue.Body.jsonData = jsonData;
            return ((Service_UAEPassCall.Service_UAEPassCallSoap)(this)).SMART_UnifiedGetURLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service_UAEPassCallSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service_UAEPassCallSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service_UAEPassCallSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://unifiedgate.moj.gov.ae/soap_uaepass/Service_UAEPassCall.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service_UAEPassCallSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://unifiedgate.moj.gov.ae/soap_uaepass/Service_UAEPassCall.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service_UAEPassCallSoap,
            
            Service_UAEPassCallSoap12,
        }
    }
}
