//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSServiceReference.SMSServiceSoap")]
    public interface SMSServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSMSList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SMSServiceReference.sendSMSListResponse> sendSMSListAsync(SMSServiceReference.sendSMSListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSMSStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SMSServiceReference.getSMSStatusResponse> getSMSStatusAsync(SMSServiceReference.getSMSStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationHeader
    {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_getSMSSendListStatus_Result
    {
        
        private int messageIDField;
        
        private string mobNoField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MobNo
        {
            get
            {
                return this.mobNoField;
            }
            set
            {
                this.mobNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_getSMSSendListStatus_Response
    {
        
        private int responseCodeField;
        
        private string responseDescriptionField;
        
        private sp_getSMSSendListStatus_Result[] sMSSendListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public sp_getSMSSendListStatus_Result[] SMSSendList
        {
            get
            {
                return this.sMSSendListField;
            }
            set
            {
                this.sMSSendListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_getSMSSendListStatusBySourceSystemId_Result
    {
        
        private int messageIDField;
        
        private string phoneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PhoneNo
        {
            get
            {
                return this.phoneNoField;
            }
            set
            {
                this.phoneNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_Insert_SMSSendList_Response
    {
        
        private int responseCodeField;
        
        private string responseDescriptionField;
        
        private int successMessageCntField;
        
        private int failedMessageCntField;
        
        private System.Nullable<decimal> messageRequestIdField;
        
        private sp_getSMSSendListStatusBySourceSystemId_Result[] recordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SuccessMessageCnt
        {
            get
            {
                return this.successMessageCntField;
            }
            set
            {
                this.successMessageCntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int FailedMessageCnt
        {
            get
            {
                return this.failedMessageCntField;
            }
            set
            {
                this.failedMessageCntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> MessageRequestId
        {
            get
            {
                return this.messageRequestIdField;
            }
            set
            {
                this.messageRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public sp_getSMSSendListStatusBySourceSystemId_Result[] Records
        {
            get
            {
                return this.recordsField;
            }
            set
            {
                this.recordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendSMSListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SMSServiceReference.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SenderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SourceSystemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MessageRequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string MessageText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ToPhoneNoList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string ScheduledMSG;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string ScheduledFromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string ScheduledToDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string AdditionalParm;
        
        public sendSMSListRequest()
        {
        }
        
        public sendSMSListRequest(SMSServiceReference.AuthenticationHeader AuthenticationHeader, string SenderID, string SourceSystemId, string MessageRequestId, string MessageText, string ToPhoneNoList, string Language, string Priority, string ScheduledMSG, string ScheduledFromDate, string ScheduledToDate, string AdditionalParm)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.SenderID = SenderID;
            this.SourceSystemId = SourceSystemId;
            this.MessageRequestId = MessageRequestId;
            this.MessageText = MessageText;
            this.ToPhoneNoList = ToPhoneNoList;
            this.Language = Language;
            this.Priority = Priority;
            this.ScheduledMSG = ScheduledMSG;
            this.ScheduledFromDate = ScheduledFromDate;
            this.ScheduledToDate = ScheduledToDate;
            this.AdditionalParm = AdditionalParm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendSMSListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSServiceReference.sp_Insert_SMSSendList_Response sendSMSListResult;
        
        public sendSMSListResponse()
        {
        }
        
        public sendSMSListResponse(SMSServiceReference.sp_Insert_SMSSendList_Response sendSMSListResult)
        {
            this.sendSMSListResult = sendSMSListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSMSStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSMSStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SMSServiceReference.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MessageID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SourceSystemId;
        
        public getSMSStatusRequest()
        {
        }
        
        public getSMSStatusRequest(SMSServiceReference.AuthenticationHeader AuthenticationHeader, string MessageID, string SourceSystemId)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.MessageID = MessageID;
            this.SourceSystemId = SourceSystemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSMSStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSMSStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSServiceReference.sp_getSMSSendListStatus_Response getSMSStatusResult;
        
        public getSMSStatusResponse()
        {
        }
        
        public getSMSStatusResponse(SMSServiceReference.sp_getSMSSendListStatus_Response getSMSStatusResult)
        {
            this.getSMSStatusResult = getSMSStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SMSServiceSoapChannel : SMSServiceReference.SMSServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<SMSServiceReference.SMSServiceSoap>, SMSServiceReference.SMSServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SMSServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSServiceReference.sendSMSListResponse> SMSServiceReference.SMSServiceSoap.sendSMSListAsync(SMSServiceReference.sendSMSListRequest request)
        {
            return base.Channel.sendSMSListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSServiceReference.sendSMSListResponse> sendSMSListAsync(SMSServiceReference.AuthenticationHeader AuthenticationHeader, string SenderID, string SourceSystemId, string MessageRequestId, string MessageText, string ToPhoneNoList, string Language, string Priority, string ScheduledMSG, string ScheduledFromDate, string ScheduledToDate, string AdditionalParm)
        {
            SMSServiceReference.sendSMSListRequest inValue = new SMSServiceReference.sendSMSListRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.SenderID = SenderID;
            inValue.SourceSystemId = SourceSystemId;
            inValue.MessageRequestId = MessageRequestId;
            inValue.MessageText = MessageText;
            inValue.ToPhoneNoList = ToPhoneNoList;
            inValue.Language = Language;
            inValue.Priority = Priority;
            inValue.ScheduledMSG = ScheduledMSG;
            inValue.ScheduledFromDate = ScheduledFromDate;
            inValue.ScheduledToDate = ScheduledToDate;
            inValue.AdditionalParm = AdditionalParm;
            return ((SMSServiceReference.SMSServiceSoap)(this)).sendSMSListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSServiceReference.getSMSStatusResponse> SMSServiceReference.SMSServiceSoap.getSMSStatusAsync(SMSServiceReference.getSMSStatusRequest request)
        {
            return base.Channel.getSMSStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSServiceReference.getSMSStatusResponse> getSMSStatusAsync(SMSServiceReference.AuthenticationHeader AuthenticationHeader, string MessageID, string SourceSystemId)
        {
            SMSServiceReference.getSMSStatusRequest inValue = new SMSServiceReference.getSMSStatusRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.MessageID = MessageID;
            inValue.SourceSystemId = SourceSystemId;
            return ((SMSServiceReference.SMSServiceSoap)(this)).getSMSStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SMSServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.17.18.25/SmsApi/SMSService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SMSServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.17.18.25/SmsApi/SMSService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SMSServiceSoap,
            
            SMSServiceSoap12,
        }
    }
}
